.github/workflows/build.yml
Api/csharp/ArmoniK.Api/ArmoniK.Api.csproj

feature: Target Dotnet Framework 4.5.2,  4.7.2, Dotnet 5.0 and Dotnet 6.0

feature: Target Dotnet Framework 4.5.2, 4.7.2, Dotnet 5.0 and Dotnet 6.0

---

Api/csharp/ArmoniK.Api/ArmoniK.Api.csproj
Protos/V1/agent_service.proto
Protos/V1/objects.proto
Protos/V1/submitter_service.proto
Protos/V1/worker_service.proto

Split bidirectionnal stream between worker and agent in order to simplify the management of the different requests from the worker in the agent. It will also allow to have a better management of errors in requests.

breaking: split bidirectionnal stream between worker and agent

---

Api/csharp/.editorconfig

Fix https://github.com/aneoconsulting/ArmoniK/issues/473

Raised severity of IDisposable not being Disposed

---

.github/workflows/build.yml
Protos/V1/agent_common.proto
Protos/V1/agent_service.proto
Protos/V1/objects.proto
Protos/V1/result_status.proto
Protos/V1/session_status.proto
Protos/V1/sessions_common.proto
Protos/V1/sessions_service.proto
Protos/V1/submitter_common.proto
Protos/V1/submitter_service.proto
Protos/V1/task_status.proto
Protos/V1/tasks_common.proto
Protos/V1/tasks_service.proto
Protos/V1/worker_common.proto
Protos/V1/worker_service.proto

fix https://github.com/aneoconsulting/ArmoniK/issues/449
how to use formatter :
- `docker run --rm --volume "$(pwd)/Protos/V1:/workspace" --workdir /workspace bufbuild/buf format -w`

Check proto formatting

---

.gitignore
pkg/.gitignore
proto2python.sh
pyproject.toml

fix https://github.com/aneoconsulting/ArmoniK/issues/468

Add python package from protos

---

.github/workflows/build.yml
.github/workflows/build_documentations.yml
.github/workflows/release.yml
Documentation/docfx.json

Because of the addition of `.editorconfig` file, yml and json have to be formatted.

chore: format yaml files

---

README.md

fix https://github.com/aneoconsulting/ArmoniK/issues/552

docs: update readme to add exemples

---

Protos/V1/tasks_common.proto

fix: https://github.com/aneoconsulting/ArmoniK/issues/518

fix: property in tasks request

---

Protos/V1/tasks_common.proto

fix https://github.com/aneoconsulting/ArmoniK/issues/554

fix: update task to task summary

---

.github/workflows/build.yml
Documentation/api-csharp/index.md

This adds a bit more doc in C# documentation index

Add doc in C# index

---

Api/common/protofiles.sh
Api/python/proto2python.sh

- Added application service and common
- Moved proto file list to be used in other languages

Updated python package

---

.github/workflows/ci.yml
.github/workflows/release.yml

Fix https://github.com/aneoconsulting/ArmoniK/issues/632

Updated PyPI send to test on main, artifact on branches and official pypi on release

---

Protos/V1/tasks_common.proto

API update for https://github.com/aneoconsulting/ArmoniK/issues/587

Add more tasks infos in taskRaw object

---

Protos/V1/applications_common.proto

fix: https://github.com/aneoconsulting/ArmoniK/issues/668

fix: update applications field name

---

.github/workflows/release.yml

Update pipeline for small fixes:
- Add timeout
- Do not fail all builds when one fails

Add timeout and do not fail all builds when one fails

---

Protos/V1/agent_service.proto
Protos/V1/applications_common.proto
Protos/V1/applications_service.proto
Protos/V1/sessions_service.proto
Protos/V1/submitter_service.proto
Protos/V1/tasks_service.proto

fix https://github.com/aneoconsulting/ArmoniK/issues/685

fix: remove unused import

---

Protos/V1/sessions_common.proto

fix https://github.com/aneoconsulting/ArmoniK/issues/712

feat: add task options in sessions summary

---

Api/common/protofiles.sh
Api/csharp/ArmoniK.Api.Client/ArmoniK.Api.Client.csproj
Api/csharp/ArmoniK.Api.Common/ArmoniK.Api.Common.csproj
Api/csharp/ArmoniK.Api.Core/ArmoniK.Api.Core.csproj
Protos/V1/auth_common.proto
Protos/V1/auth_service.proto

fix: https://github.com/aneoconsulting/ArmoniK/issues/707

feat: add active user endpoint

---

.docs/app.config.ts
.docs/content/1.guide/1.c-sharp.md
.docs/content/1.guide/2.python.md
.docs/content/1.guide/_dir.yml
.docs/content/api/0.index.md
.docs/content/api/1.v1.md
.docs/content/api/_dir.yml
.github/workflows/deploy-docs.yml

docs: update path to proto v1

---

.github/workflows/deploy-docs.yml

ci: fix proto cache name

---

.github/workflows/semantic-pull-request.yml

ci: add a workflow to check pr title

---

.github/workflows/publish-edge.yml

It seems that we need to checkout to the right branch because I did not get the modifications made in another branch.
I tested this modification on the other pr with the issue. It fixed it.

ci: fix publish edge checkout

---

Protos/V1/tasks_common.proto

Will permit to filter tasks by many status

feat(proto): task status filter is now repeated

---

.eslintrc.js
package-lock.json
package.json
scripts/remove-useless-md.mjs

fix: protocol documentation name

---

.github/workflows/deploy-docs.yml

ci: fix deploy docs

---

.github/workflows/deploy-docs.yml

ci: fix pipeline

---

.github/workflows/publish-edge.yml

ci: fix typo in script name

---

.github/workflows/deploy-docs.yml

ci: fix docs deploy

---

.github/workflows/publish-edge.yml
.github/workflows/release.yml
scripts/publish-edge.mjs
scripts/publish.mjs

ci(angular): fix release process

---

.docs/package-lock.json
.docs/package.json

docs: update dependencies

---

Protos/V1/sessions_common.proto

chore: remove unused import

---

Protos/V1/applications_common.proto

feat: add multiple sort field when list applications

---

.docs/package.json
.docs/pnpm-lock.yaml

docs: update pnpm version

---

package.json
packages/angular/package.json
packages/angular/pnpm-lock.yaml
packages/web/package.json
packages/web/pnpm-lock.yaml
pnpm-lock.yaml

chore: update pnpm version

---

packages/angular/projects/aneoconsultingfr/armonik.api.angular/src/lib/index.ts

I'm currently trying to in use `next` (3.9.0-x) but I've import issue. This PR fix it.

fix: export in public api from angular package

---

.github/auto_assign.yml
.github/workflows/auto-assign.yml

An example: https://github.com/esoubiran-aneo/ArmoniK.Api/pull/10

ci: add auto-assign

---

packages/csharp/ArmoniK.Api.Client/Options/GrpcClient.cs
packages/csharp/ArmoniK.Api.Client/Submitter/GrpcChannelFactory.cs

Need to re-add features to manage retry and keep alive in the tcp connection

fix: retry and keep alive

---

packages/angular/projects/aneoconsultingfr/armonik.api.angular/src/lib/index.ts

We need this for the next GUI and the current in 0.9 to allow update to ArmoniK 0.14

feat: update tasks angular package

---

packages/angular/projects/aneoconsultingfr/armonik.api.angular/package.json
packages/csharp/ArmoniK.Api.Client.Test/ArmoniK.Api.Client.Tests.csproj
packages/csharp/ArmoniK.Api.Client/ArmoniK.Api.Client.csproj
packages/csharp/ArmoniK.Api.Common.Channel/ArmoniK.Api.Common.Channel.csproj
packages/csharp/ArmoniK.Api.Common/ArmoniK.Api.Common.csproj
packages/csharp/ArmoniK.Api.Core/ArmoniK.Api.Core.csproj
packages/csharp/ArmoniK.Api.Tests/ArmoniK.Api.Worker.Tests.csproj
packages/csharp/ArmoniK.Api.Worker/ArmoniK.Api.Worker.csproj
packages/web/package.json

This PR must become after https://github.com/aneoconsulting/ArmoniK.Api/pull/324

chore: release 3.9.2

---

packages/csharp/ArmoniK.Api.Client/Options/GrpcClient.cs
packages/csharp/ArmoniK.Api.Client/Submitter/GrpcChannelFactory.cs

Default timeout is too short (100 seconds)

fix: Fixed timeout issue

---

Protos/V1/tasks_common.proto
packages/angular/projects/aneoconsultingfr/armonik.api.angular/src/lib/index.ts

fix: oneOf in tasks

---

Protos/V1/applications_common.proto
packages/angular/projects/aneoconsultingfr/armonik.api.angular/src/lib/index.ts

similar fix from #339
fix #338

fix: oneOf in applications

---

Protos/V1/partitions_common.proto
packages/angular/projects/aneoconsultingfr/armonik.api.angular/src/lib/index.ts

fix: oneOf in partitions

---

Protos/V1/results_common.proto
packages/angular/projects/aneoconsultingfr/armonik.api.angular/src/lib/index.ts

fix: oneOf in results

---

Protos/V1/partitions_common.proto
Protos/V1/partitions_fields.proto
Protos/V1/partitions_filters.proto
Protos/V1/partitions_service.proto
Protos/V1/sort_direction.proto
Protos/V1/versions_common.proto
Protos/V1/versions_service.proto

Fix: https://github.com/aneoconsulting/ArmoniK.Api/issues/356

refactor: uniformize C# namespaces

---

Protos/V1/tasks_common.proto
Protos/V1/tasks_service.proto
packages/angular/projects/aneoconsultingfr/armonik.api.angular/src/lib/index.ts
packages/cpp/ArmoniK.Api.Client/CMakeLists.txt
packages/python/src/armonik/common/objects.py
packages/python/tests/tasks_test.py

Fix: https://github.com/aneoconsulting/ArmoniK.Api/issues/371

refactor: rename TaskRaw to TaskDetailed

---

.docs/content/2.usage/use-armonik-api-in-an-angular-app.md

docs: update angular guide

---

renovate.json

chore: update renovate config for ArmoniK.Utils

---

packages/cpp/ArmoniK.Api.Client/header/tasks/Task.h
packages/cpp/ArmoniK.Api.Client/header/tasks/TasksClient.h
packages/cpp/ArmoniK.Api.Client/source/tasks/TasksClient.cpp
packages/cpp/ArmoniK.Api.Common/header/objects/Task.h
packages/cpp/ArmoniK.Api.Tests/source/TasksClientTest.cpp

- To be rebased once #435 is merged

refactor: Task service wrapper cpp

---

packages/angular/projects/aneoconsultingfr/armonik.api.angular/src/lib/index.ts

fix: missing filterDuration and filterDurationOperation exports in angular package

---

packages/python/src/armonik/worker/__init__.py
packages/python/src/armonik/worker/taskhandler.py
packages/python/tests/conftest.py
packages/python/tests/test_taskhandler.py
packages/python/tests/test_worker.py

- fix: Python API fix tasks service
- feat: Python API update taskhandler and worker

feat: Python API update taskhandler and worker

---

packages/python/src/armonik/client/events.py
packages/python/src/armonik/common/events.py

- fix: Python API event client wait_for_result_availability method
- fix: Python event client

fix: Python API event client wait_for_result_availability method

---

packages/python/src/armonik/common/objects.py
packages/python/src/armonik/worker/taskhandler.py
packages/python/tests/test_taskhandler.py

fix: Fixed result parsing in task handler

feat: Task Handler cleanup

---

packages/python/src/armonik/client/tasks.py
packages/python/src/armonik/common/objects.py

fix: task from task summary

---

.github/workflows/ci.yml
.github/workflows/publish-edge.yml
.github/workflows/release.yml
packages/java/pom.xml
scripts/update-versions.ts
scripts/verify-versions.ts
scripts/versions/_contants.ts

ci: add java package

---

.github/workflows/test.yml
packages/cpp/ArmoniK.Api.Common/header/options/ControlPlane.h
packages/cpp/ArmoniK.Api.Common/source/options/ControlPlane.cpp
packages/cpp/ArmoniK.Api.Common/source/utils/Configuration.cpp
packages/cpp/ArmoniK.Api.Tests/source/MockTest.cpp
packages/cpp/ArmoniK.Api.Tests/source/common.cpp
packages/cpp/tools/run_test.sh

Standardizes environment variables names across languages 
This PR standardizes the C++ configuration environment variables to match those used in C#.
Makes it easy to define variables in different environments without duplicating them. Impacts the use of future versions of the C++ SDK.

chore: Use uniform config variables cpp

---

packages/cpp/tools/packaging/make-deb.sh
packages/cpp/tools/packaging/make-rpm.sh
packages/cpp/tools/packaging/make-tar.gz.sh
packages/cpp/tools/packaging/tgz_alpine.Dockerfile

ci broken when creating binary api client in tar.gz format
CI back to green

fix: correct binary client creation based on alpine

---

packages/python/src/armonik/common/filter/filter.py

Error messages of the FilterError exception for the Python APi are dirty.
Modify error messages to make them more clear.
Manual tests only.
No impact.
No.

feat: cleaner error messages for Python filters

---

packages/python/fix_imports.py
packages/python/src/armonik/common/filter/filter.py

correct python linting 
N/A
None

fix: python linter ruff

---

.github/workflows/ci.yml

Simplify formatting resolution conflicts that appear in the pipeline by generating and uploading a `diff.patch` file.  Patch file  can be applied locally to comply with the desired formatting  
Modify corresponding action to generate patch and upload artifact
not applicable
None

chore: generate and upload patch if c# format failed

---

packages/rust/armonik/Cargo.toml
scripts/update-versions.ts
scripts/verify-versions.ts
scripts/versions/_contants.ts

Cargo.toml is not automatically updated by `scripts/update-versions.ts` script.
Add files and patterns related to rust Cargo.toml

ci: script update rust version
