Protos/V1/applications_common.proto, Protos/V1/applications_service.proto, Protos/V1/results_common.proto
Make the API coherent.
- Use timestamp for dates instead of strings
- Fix Applications namespace
- Add corresponding fields in Applications list orderby
=> Small fixes for APIs

packages/csharp/ArmoniK.Api.Client/Submitter/SubmitterClientExt.cs, packages/csharp/ArmoniK.Api.Worker/Worker/TaskHandler.cs, packages/csharp/ArmoniK.Api.Worker/Worker/TaskRequestExtensions.cs
Previously, we were making copies when giving byte arrays to gRPC ByteStrings. This PR fixes it by using UnsafeOpterations.UnsafeWrap to only pass references instead of copying the data.
=> perf: avoid making copies when using gRPC ByteStrings

.github/workflows/publish-edge.yml
This PR fixes the version generate by codacy git-version when running on main branch.
=> fix: Publish Edge pipeline does not generate the right tag when on main branch

.github/workflows/publish-edge.yml, .gitignore, packages/csharp/ArmoniK.Api.Tests/TaskHandlerTest.cs, packages/csharp/ArmoniK.Api.Worker/AssemblyInfo.cs, packages/csharp/ArmoniK.Api.Worker/Worker/TaskHandler.cs
When moving TaskHandler from Core to Api, the tests became obsolete. This PR adds new tests for TaskHandler.
fix https://github.com/aneoconsulting/ArmoniK/issues/341
=> test: Add tests for TaskHandler class

scripts/versions/_contants.ts, scripts/versions/_readAndFind.ts
=> chore: verify versions

.github/workflows/validate-docs-generation.yml
Stop CI and Validate Doc workflows from cancelling each other since they have the same concurrency group.
=> ci: stop two workflows from cancelling each others

packages/csharp/ArmoniK.Api.Common/Utils/LoggerExt.cs
Add duration of the execution of the LogFunction extension. Start timer for the first log and print the duration between the start and the last log.
=> feat: Add duration in C# LogFunction

.vscode/extensions.json, .vscode/settings.json
- suggest extensions to use for vscode
- Configure proto3 extension to validate and generate grpc code from proto
=> build: configure protoc extension and suggest extensions for vscode

packages/csharp/ArmoniK.Api.Client/ArmoniK.Api.Client.csproj, packages/csharp/ArmoniK.Api.Client/Options/GrpcClient.cs, packages/csharp/ArmoniK.Api.Client/Submitter/GrpcChannelFactory.cs, packages/csharp/ArmoniK.Api.Common.Channel/ArmoniK.Api.Common.Channel.csproj, packages/csharp/ArmoniK.Api.Core/ArmoniK.Api.Core.csproj, packages/csharp/ArmoniK.Api.Worker/ArmoniK.Api.Worker.csproj
mTLS support was implemented incorrectly, this PR aims at correcting this problem and have a functional implementation.
Note that it *should* only support TLS 1.2 at most, as TLS 1.3 is not supported on netstandard.
=> feat: Added mTLS support to C# Api

.github/workflows/release.yml, scripts/verify-versions.ts
When we do a release, this will check if we forgot to change the version of the packages, preventing issues where Python would send a new version to pypi but C# packages would be the old version
=> ci: Added version check for release

.vscode/extensions.json
There is no yml file (others than Actions) so this extension is not necessary. If we want, we can add the GitHub Actions extension.
=> chore: remove unused vscode extension

.github/workflows/publish-edge.yml
Move away from deprecated api used in th pypi action
=> ci: update params to publish to pypi

.vscode/settings.json, README.md
In order to easily find packages on registry, I added links to them using nice bagde. These are also used in other packages like "order-github-changelog" or "generate-next-version".
=> docs: add packages version

.github/workflows/publish-edge.yml, renovate.json
I group renovate PR using [datasources](https://docs.renovatebot.com/modules/datasource/). This will simplify the review and the merge.
For security reasons, I use "helpers:pinGitHubActionDigests" to pin actions to a specific commit.
An example of the config: https://github.com/esoubiran-aneo/ArmoniK.Api
=> chore: group renovate's pr using datasources

packages/csharp/ArmoniK.Api.Client/ArmoniK.Api.Client.csproj, packages/csharp/ArmoniK.Api.Client/Submitter/GrpcChannelFactory.cs, packages/csharp/ArmoniK.Api.Common/ArmoniK.Api.Common.csproj, packages/csharp/ArmoniK.Api.Core/ArmoniK.Api.Core.csproj, packages/csharp/ArmoniK.Api.Worker/ArmoniK.Api.Worker.csproj
Fixed error thrown by the channel having 2 http handlers (HttpHandler AND HttpClient) (https://github.com/aneoconsulting/ArmoniK.Extensions.Csharp/actions/runs/5378150560/jobs/9757621647?pr=190#step:9:279)
=> fix: fixed double http handler

renovate.json
In order to easily merge PR from renovate, we need to split npm packages depending of the projet.
You can find an example of the result here https://github.com/esoubiran-aneo/ArmoniK.Api/issues/3
=> chore: update renovate config to split npm

.github/workflows/semantic-pull-request.yml
The CI "Lint PR" is very fast and we have a concurrency issue. I thing that we case easily remove the cancel-in-progress to avoid that main cancel a branch.
see https://github.com/aneoconsulting/ArmoniK.Api/actions/workflows/semantic-pull-request.yml to view some Actions cancelled witout reason.
=> ci: fix concurrency issue in lint pr

.github/workflows/publish-edge.yml
If the edge package to release should have been a normal release and not an edge package, prevents the publish edge from publishing
=> ci: release edge on tag

packages/cpp/ArmoniK.Api.Common/CMakeLists.txt, packages/cpp/ArmoniK.Api.Common/source/logger/formatter.cpp, packages/cpp/tools/BuildEnv.Dockerfile, packages/cpp/tools/Dockerfile.ubuntu, packages/cpp/tools/Dockerfile.worker
Due to license constraints, we cannot ship out the fmt library. Thus a fetchcontent is not possible
Also found an issue that appears only at link time (formatter_plain not defined)
=> fix: formatter and fmt installation

.vscode/settings.json
fix #235
I move the folder under `packages/csharp` in order to have the same structure as `angular` and to let the ability to add it for other languages in the future.
=> chore: update gen csharp path

Protos/V1/agent_common.proto, Protos/V1/agent_service.proto, Protos/V1/worker_common.proto, Protos/V1/worker_service.proto, packages/csharp/ArmoniK.Api.Mock/Services/Agent.cs, packages/csharp/ArmoniK.Api.Tests/TaskHandlerTest.cs, packages/csharp/ArmoniK.Api.Worker/Worker/ITaskHandler.cs, packages/csharp/ArmoniK.Api.Worker/Worker/TaskHandler.cs, packages/csharp/ArmoniK.Api.Worker/Worker/WorkerStreamWrapper.cs
This PR changes the way data should be sent between Worker and Scheduling Agent to use files in a shared directory instead of gRPC streams.
Rationale:
Rework communications between scheduling agent and worker so that there is no streams and pass data through file in a shared volume. This will allow some nice optimisations such as:
What changed ?
- Worker `Process` RPC is now an Unitary Call (no streams) with a `data_location` folder in which Payload and Data Dependencies are located as file whose name is the ID of the input
- Agent Get*Data are now Unitary Calls too : The call returns when expected data are located in the `data_location` folder as file whose name is the ID of the required data
- Agent `UploadResultData` and `SendResult` became `NotifyResultData`. Results should be stored …
=> feat: send data between agent and worker through files instead of stream-based requests

Protos/V1/health_checks_common.proto, Protos/V1/health_checks_service.proto, packages/common/protofiles.sh, packages/cpp/ArmoniK.Api.Client/CMakeLists.txt, packages/csharp/ArmoniK.Api.Client/ArmoniK.Api.Client.csproj, packages/csharp/ArmoniK.Api.Common/ArmoniK.Api.Common.csproj, packages/csharp/ArmoniK.Api.Core/ArmoniK.Api.Core.csproj, packages/csharp/ArmoniK.Api.Mock/Program.cs, packages/csharp/ArmoniK.Api.Mock/Services/HealthChecks.cs
fix #168
This will allow connected client to know is the API is up and running (so client can communicate with it) and if the cluter is up and running.
=> feat: add health checks

.github/workflows/publish-edge.yml, .github/workflows/release.yml
The pre-version should be available only on https://test.pypi.org
=> chore: remove pre-version package to be published on Pypi website

packages/csharp/ArmoniK.Api.Common/Options/ComputePlane.cs, packages/csharp/ArmoniK.Api.Worker/Worker/WorkerStreamWrapper.cs
Change the default option and abort immediately upon cancellation.
This is to limit the edge case that a task cancellation that is not catched would make the next task to crash and being retried.
=> fix: Abort immediately upon cancellation

.github/workflows/test.yml, packages/csharp/ArmoniK.Api.Client.Test/ArmoniK.Api.Client.Tests.csproj, packages/csharp/ArmoniK.Api.Client.Test/ConnectivityKind.cs, packages/csharp/ArmoniK.Api.Client.Test/ConnectivityTest.cs, packages/csharp/ArmoniK.Api.Mock/ArmoniK.Api.Mock.csproj, packages/csharp/ArmoniK.Api.Mock/Program.cs, scripts/certs.sh
Add support for TLS for ArmoniK.Api.mock.
This enables to test within the Api repository the client channel creation for TLS/mTLS.
=> ci: Add TLS support for Mock

packages/csharp/ArmoniK.Api.Client/Options/GrpcClient.cs, packages/csharp/ArmoniK.Api.Client/Submitter/GrpcChannelFactory.cs
On windows, a connection allocate a port that remains allocated 4 minutes after closing. When the server request connection closing after each request, we end up exhausting ports very quickly.
Adding the option to reuse ports enable to work around this limitation.
=> fix: Add ReusePorts option

packages/python/src/armonik/common/enumwrapper.py, packages/python/src/armonik/common/objects.py
- feat: turn enumwrappers into real python enumerators
- fix: correctly convert TaskOptions option property into Python dictionnary
So far, the API wrappers for enumerators are not “real” Python enumerators. This makes it difficult to obtain the name associated with the value of enumerator elements.
This change fixes this problem by making each enumerator wrapper a “real” Python enumerator.
It also fixes a minor bug in the conversion of the TaskOptions option field to a native Python dictionary.
A few manual tests in addition to unit tests.
This changes should have no impact.
=> feat: turn enumwrappers into real python enumerators

packages/python/ruff.toml
Ruff, the Python linter, displays a warning message because of the use of a deprecated configuration setting.
This change removes the deprecated configuration setting from the ruff configuration.
The linting style works properly with this change.
This change has no impact.
=> style: remove a deprecated configuration setting

packages/python/src/armonik/common/__init__.py, packages/python/src/armonik/worker/__init__.py
Some new features implemented by the Python API are not exposed at the module level.
Fixes the imports to expose these features.
Tested using the CI.
No impact.
=> fix: expose some missing functions of the common and worker modules

.github/workflows/ci.yml, .github/workflows/test.yml, packages/cpp/ArmoniK.Api.Client/header/submitter/SubmitterClient.h, packages/cpp/ArmoniK.Api.Common/source/utils/ChannelArguments.cpp
There are multiple errors in the pipelines currently:
- Windows tests for Rust fail with the following error: "No connection could be made because the target machine actively refused it."
- The formatting rules in C++ have changed due to the image upgrade from ubuntu-22.04 to ubuntu-24.04
- Dotnet installation has changed due to the image upgrade from ubuntu-22.04 to ubuntu-24.04
Disable the windows tests for Rust while waiting for a proper fix.
Update the C++ code to adhere to the new formatting rules.
Force the installation of both dotnet 6 and dotnet 8 in all circumstances
The proper fix for Rust would be to enable port reuse, but this would require to reimplement a bunch of code to create a new channel.
=> ci: Fix pipelines

packages/python/src/armonik/common/objects.py
The field parent_partition_ids of the Partition object of the Python API is a gRPC list object but is used as-is in Partition's from_message.
Converting it to a Python list.
Passes Python tests for this repo, I've also tested it in the ArmoniK.Admin.CLI.
Won't directly break any code that converts the object `list(my_list) is list` but if it was being treated as a RepeatedScalarFieldContainer (which should not be the case!) then said code might break.
Not applicable.
=> fix: parent_partition_ids field in Partition object of Python API

packages/csharp/ArmoniK.Api.Common/ArmoniK.Api.Common.csproj, packages/csharp/ArmoniK.Api.Common/Options/ComputePlane.cs, packages/csharp/ArmoniK.Api.Common/Options/GrpcChannel.cs, packages/csharp/ArmoniK.Api.Common/Utils/ConfigurationExt.cs, packages/csharp/ArmoniK.Api.Tests/WorkerServerTest.cs, packages/csharp/ArmoniK.Api.Worker/Utils/WorkerServer.cs
PR https://github.com/aneoconsulting/ArmoniK.Api/pull/583 added support to allow the usage of a tcp socket between the agent and the worker. There are still issues with connection (for Java grpc) which are solved deactivating some keep-alive options   . This PR exposes those options so they can be set via environmental variables during deployment. 
Added the two relevant Keep-alive options  as members of the `GrpcChannel` class, the options are deactivated by setting
them as `TimeSpan.MaxValue`. 
In order to allow the user to specify this in the corresponding environment variables, for example to disable the `KeepAlivePingTimeout` in the `WorkerChannel`,  we make use of the environment variable:
```hcl 
"ComputePlane__WorkerChannel__KeepAlivePingTimeout=MaxValue"
```
manually parse the …
=> chore: parametrize keep alive options

packages/rust/armonik/Cargo.lock, packages/rust/armonik/Cargo.toml, packages/rust/armonik/build.rs, packages/rust/armonik/src/api/v3.rs, packages/rust/armonik/src/client/agent.rs, packages/rust/armonik/src/client/applications.rs, packages/rust/armonik/src/client/auth.rs, packages/rust/armonik/src/client/events.rs, packages/rust/armonik/src/client/health_checks.rs, packages/rust/armonik/src/client/mod.rs, packages/rust/armonik/src/client/partitions.rs, packages/rust/armonik/src/client/results.rs, packages/rust/armonik/src/client/sessions.rs, packages/rust/armonik/src/client/submitter.rs, packages/rust/armonik/src/client/tasks.rs, packages/rust/armonik/src/client/versions.rs, packages/rust/armonik/src/client/worker.rs, packages/rust/armonik/src/objects/health_checks/check.rs, packages/rust/armonik/src/objects/health_checks/mod.rs, packages/rust/armonik/src/objects/health_checks/service_health.rs, packages/rust/armonik/src/objects/health_checks/status.rs, packages/rust/armonik/src/objects/mod.rs, packages/rust/armonik/src/objects/tasks/mod.rs
HealthCheck service was missing, and the interface to get a typed client was messy.
Implement the missing HealthCheck service.
Cleanup the client interface.
This is a breaking change relative to the Rust API, but as the rust package is still on beta, this is fine.
=> chore: Cleanup client interface for Rust API

packages/rust/armonik/Cargo.lock, packages/rust/armonik/Cargo.toml, packages/rust/armonik/src/client/agent.rs, packages/rust/armonik/src/client/events.rs, packages/rust/armonik/src/client/mod.rs, packages/rust/armonik/src/client/results.rs, packages/rust/armonik/src/client/submitter.rs
`async_trait` makes the method futures either all sends, or all not send.
Remove the async_trait and use async in trait feature of recent Rust versions.
It has been tested in the load balancer.
This is a breaking change, but as the rust package is still in beta, this is fine.
=> fix: Remove async_trait from client code

packages/python/src/armonik/client/results.py, packages/python/src/armonik/common/filter/_filter_field.py, packages/python/src/armonik/common/objects.py, packages/python/tests/test_results.py
The RPC for importing result data is not implemented in the Python API.
Updated the Result object to add the opaque_id field and implemented the import_data method on ArmoniKResults class.
Added a new unit test.
No impact.
Not applicable.
=> feat: Add import result data method for Python API

.github/workflows/publish-edge.yml, .github/workflows/test.yml, .vscode/settings.json
Allow to publish nuget packages produced by updates from Renovate so that we can test if they are still compatible with other projects.
- Change pipeline job conditions so that nuget packages are published when Renovate opens PRs
- Use the CI
NA
NA
=> ci: move test in test ci and allow nuget package publishing on renovate PRs

packages/python/src/armonik/worker/taskhandler.py, packages/python/tests/test_taskhandler.py
Fixes for the task handler
Iteracting over a dictionary should yield keys, not key, value pairs
Tested with subtasking sample
[Discuss the impact of your modifications on ArmoniK. This might include effects on performance, configuration, documentation, new dependencies, or changes in behaviour.]
=> fix: Fix Python TaskHandler

Protos/V1/results_common.proto, Protos/V1/results_fields.proto, packages/rust/armonik/src/client/results.rs, packages/rust/armonik/src/objects/results/create.rs, packages/rust/armonik/src/objects/results/create_metadata.rs, packages/rust/armonik/src/objects/results/field.rs, packages/rust/armonik/src/objects/results/raw.rs
Allow users to specify data that will not be deleted by ArmoniK. Used in combination with import, it ensures data managed outside of ArmoniK to not be deleted by ArmoniK.
- Add `manual_deletion` option during results metadata creation
- Add missing fields for filtering
- Implement Rust client side
- Rust unit tests were modified accordingly and are passing.
- This option should be supported in ArmoniK.Core in the future
- This option has to be added into other programming languages
=> feat: option to turn off data deletion by armonik

.docs/conf.py
To improve navigation and help users find relevant information more easily.
Enabling search functionality on ReadTheDocs by setting html_search = True in conf.py
=> docs: add search in readthedocs

.readthedocs.yaml, scripts/generate-csharp-doc.sh
Reduce the failure rate of documentation builds.
Install dotnet with apt-get through readthedocs `apt_packages`  instead of using curl to download dotnet installer and execute it to install dotnet.  Curl step was failing a lot.
Documentation is building properly.
Decrease the burden of having a "green" pipeline.
=> docs: Fix read the doc build

.github/workflows/ci.yml, .github/workflows/test.yml
Protoc install might fail when installed from apt.
Windows server 2019 has been deprecated from github runners.
Install protoc with taiki-e/install-action, and remove Windows server 2019 tests.
=> ci: remove windows 2019 and fix protoc install

packages/python/src/armonik/worker/taskhandler.py
Encountered error when trying to set the task options of a task that's being instantiated from a Python worker (via sub-tasking). 
- Changed the SubmitTaskRequest to just take in the default_task_options on creation. (Another approach would be to still use the if statement and a `CopyFrom` ?)
The unit tests in this repo are still passing
Not Applicable.
Not Applicable.
=> fix: Properly passing in task options in the worker's task handler
